// src/services/ai.service.js
const { GoogleGenerativeAI } = require("@google/generative-ai");

const API_KEY = process.env.GOOGLE_GEMINI_KEY;

if (!API_KEY) {
  console.error("🔑 Gemini API Key not found. Set GOOGLE_GEMINI_KEY in your .env");
}

const ai = new GoogleGenerativeAI(API_KEY);

const model = ai.getGenerativeModel({
  // use a model available in your console; gemini-2.5-flash was shown in your screenshots
  model: "gemini-2.5-flash",
  systemInstruction: `
    You are a meticulous senior software engineer, code reviewer, and mentor. Your mission:
    - Act as a professional code reviewer: find bugs, propose fixes, and explain reasoning clearly.
    - Provide runnable fixed code in the same programming language and preserve original style where reasonable.
    - If you change code, provide a unified diff or annotate changed lines.
    - If the code involves algorithms/DSA, always include Time Complexity (Big-O) and Space Complexity with short proofs/derivations.
    - Provide an ordered step-by-step approach a developer should follow to implement fixes and optimizations.
    - Produce helpful test cases (unit tests or sample inputs/outputs) and list edge cases.
    - Highlight security, concurrency, or performance pitfalls and recommend mitigations.
    - Use structured Markdown headings and concise bullet points. Put code in fenced blocks with the language tag.
    - If any information is missing (e.g., input format, expected behavior), state what is missing and propose reasonable assumptions — but do not ask the user to wait; proceed with best-effort assumptions.
    - Keep answers precise, avoid unnecessary verbosity.
  `,
});

/**
 * generateContent(code) -> { review: string }
 */
async function generateContent(code) {
  if (!code) throw new Error("No code provided to AI service");

  try {
    console.log("🧠 Sending code to Gemini API...");
    // If your SDK accepted a single string earlier, keep that. This call matches previous usage:
    const result = await model.generateContent(code);

    // result.response.text() used previously; keep same guard
    let raw = "";
    if (result && typeof result.response?.text === "function") {
      raw = await result.response.text();
    } else if (result && typeof result === "string") {
      raw = result;
    } else if (result && result.response && result.response.text) {
      // fallback
      raw = String(result.response.text);
    }

    if (!raw) {
      console.warn("⚠️ Gemini returned an empty response");
      return { review: "⚠️ No review generated by the AI (empty response)." };
    }

    // If the model returns JSON object in string form, try to parse it and extract 'review'
    let reviewText = raw;
    // sometimes SDK returns JSON with top-level object
    if (typeof reviewText === "string" && reviewText.trim().startsWith("{")) {
      try {
        const parsed = JSON.parse(reviewText);
        if (parsed && parsed.review) reviewText = parsed.review;
        else reviewText = JSON.stringify(parsed, null, 2);
      } catch (err) {
        // not JSON — that's okay, continue with raw string
      }
    }

    // Clean up common artifacts the model sometimes emits
    // 🧹 Clean up and auto-format AI text
reviewText = String(reviewText)
  .replace(/\[object Object\]/g, "")
  .replace(/^---.*$/gm, "")
  .replace(/^\+\+\+.*$/gm, "")
  .replace(/^@@.*$/gm, "")
  .trim();

// 🪄 Detect and wrap raw code snippets (no ``` present)
const codePattern =
  /(function\s+\w+\s*\(.*\)\s*\{[\s\S]*?\})|((const|let|var)\s+\w+\s*=\s*.*;?)/gm;

if (!reviewText.includes("```")) {
  reviewText = reviewText.replace(codePattern, (match) => {
    // Wrap detected code in a code block
    return `\n\`\`\`js\n${match.trim()}\n\`\`\`\n`;
  });
}

// 🧠 Final fallback
if (!reviewText.trim()) reviewText = "⚠️ No review generated.";



    console.log("✅ Received review from Gemini (trimmed length):", reviewText.length);
    return { review: reviewText };
  } catch (err) {
    console.error("❌ AI Review Error:", err?.message || err);
    // Return friendly message rather than empty body so frontend will show it
    return { review: `⚠️ AI Error: ${err?.message || "unknown error"}` };
  }
}

module.exports = generateContent;
